### ISSUE TITLE
waiting for selector `div.dashboardMetaData` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by psacchitella** [structurizr/puppeteer#13]
I am getting the following errors.
Signing in...
/Users/user1/git-all-repo/pluto-git/C4-Puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528
            const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: waiting for selector `div.dashboardMetaData` failed: timeout 30000ms exceeded
    at new WaitTask (/Users/user1/git-all-repo/pluto-git/C4-Puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)
    at DOMWorld.waitForSelectorInPage (/Users/user1/git-all-repo/pluto-git/C4-Puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26)
    at internalHandler.waitFor (/Users/user1/git-all-repo/pluto-git/C4-Puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/Users/user1/git-all-repo/pluto-git/C4-Puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29)
    at Frame.waitForSelector (/Users/user1/git-all-repo/pluto-git/C4-Puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:942:51)
    at Page.waitForSelector (/Users/user1/git-all-repo/pluto-git/C4-Puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33)
    at /Users/user1/git-all-repo/pluto-git/C4-Puppeteer/export-private-diagrams-to-html.js:38:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.5.0

**Comment by psacchitella** [comment]
I am also unable to run the export scripts from Github actions:
Opening diagrams in workspace 1...
/home/runner/work/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isDiagramRendered')
    at eval (eval at waitForPredicatePageFunction (:3:23), <anonymous>:3:31)
    at onRaf (__puppeteer_evaluation_script__:56:25)
    at pollRaf (__puppeteer_evaluation_script__:47:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:8:22)
    at ExecutionContext._evaluateInternal (/home/runner/work/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WaitTask.rerun (/home/runner/work/puppeteer/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:551:23)

**Comment by simonbrowndotje** [comment]
Try `div#dashboard` instead of `div.dashboardMetaData`.

**Comment by psacchitella** [comment]
I submitted a pull request in April that fixes it. I just forgot I did it.Sent from my iPadOn Nov 6, 2022, at 11:13 AM, Simon Brown ***@***.***> wrote:﻿
Closed #13 as completed via b072087.
