### ISSUE TITLE
Error when running export-express-diagram.js: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by aviflax** [structurizr/puppeteer#2]
I’ve cloned the repo, and I’m running the script like so: `$ node export-express-diagram.js png /path/to/valid/diagram.yaml`

The script almost immediately prints out an error message, then hangs.

The error:

```
TypeError: Cannot read property 'replace' of undefined
    at exportDiagramAndKeyToPNG (/Users/avi.flax/dev/floss/structurizr/puppeteer/export-express-diagram.js:51:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

(I’ve omitted the output related to a `UnhandledPromiseRejectionWarning` and `DeprecationWarning`.)

My environment:

* Puppeteer 1.10.0
* Node 10.13.0
* MacOS 10.13.6

Thanks!

**Comment by simonbrowndotje** [comment]
Apologies, that should be working now.
