### ISSUE TITLE
export-private-diagrams-to-html.js times out

### ISSUE THREAD

**Issue by psacchitella** [structurizr/puppeteer#9]
I am seeing the following error when I tried to use 
export-private-diagrams-to-html.js

On either the on premises or the cloud version.

node export-private-diagrams-to-html.js http://localhost:9191/ structurizr password 1

Signing in...

/Users/sacchitp/git-all-repo/git-pub/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528

            const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);

                                 ^

TimeoutError: waiting for selector `div.dashboardMetaData` failed: timeout 30000ms exceeded

    at new WaitTask (/Users/sacchitp/git-all-repo/git-pub/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)

    at DOMWorld.waitForSelectorInPage (/Users/sacchitp/git-all-repo/git-pub/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26)

    at Object.internalHandler.waitFor (/Users/sacchitp/git-all-repo/git-pub/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)

    at DOMWorld.waitForSelector (/Users/sacchitp/git-all-repo/git-pub/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29)

    at Frame.waitForSelector (/Users/sacchitp/git-all-repo/git-pub/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:942:51)

    at Page.waitForSelector (/Users/sacchitp/git-all-repo/git-pub/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2359:33)

    at /Users/sacchitp/git-all-repo/git-pub/puppeteer/export-private-diagrams-to-html.js:32:14

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by psacchitella** [comment]
Changing this 
`await page.waitForSelector('div.dashboardMetaData');`
to this
`await page.waitForSelector('div.workspaceThumbnail');`
Fixed the script.

**Comment by simonbrowndotje** [comment]
Thanks!
